//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctaxi_v1.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriversTable
    {
        public int Id { get; set; }
        public string licenseNum { get; set; }
        public string fullName { get; set; }
        public string phoneNum { get; set; }
        public Nullable<System.DateTime> dateBegin { get; set; }
        public Nullable<System.DateTime> dateCheck { get; set; }
    }
}
